# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  artifactName: 'SlackWriterArtifact'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build --configuration $(buildConfiguration)'
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    testRunTitle: 'dotnet test'

# Package a project
#- task: NuGetCommand@2
#  displayName: 'Nuget Pack'
#  inputs:
#    command: 'pack'
#    packagesToPack: '**/*.csproj'
#    packDestination: '$(Build.ArtifactStagingDirectory)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: '$(buildConfiguration)'
    nobuild: true
    versioningScheme: 'off'
    


#- task: NuGetCommand@2
#  displayName: 'nuget push'
#  inputs:
#    command: 'push'
#    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
#    nuGetFeedType: 'internal'
#    publishVstsFeed: '4b6b89b8-326a-4d57-9aa1-84d930b6dcb3'