# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'
  
  variables:
    buildConfiguration: 'Release'
    artifactName: 'SlackWriterArtifact'
    nugetPackageLoc: '/home/vsts/work/1/s/SlackWriter.Core/bin/Release'
    packageVersion: '1.0.6'
  
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build --configuration $(buildConfiguration)'
    inputs:
      command: 'build'
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      testRunTitle: 'dotnet test'
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: 'pack'
  - task: Bash@3
    displayName: 'dotnet nuget push'
    inputs:
      targetType: 'inline'
      script:
        # go to the output dir for the nuget package and push it to nuget
        cd /home/vsts/work/1/a &&
        dotnet nuget push SlackWriter.$(packageVersion).nupkg -k $(NugetApiKey) -s https://api.nuget.org/v3/index.json --skip-duplicate